Allow leapp packages to be removed
redhat-cop/infra.leapp pull request #153
Opened 2024-01-29 16:11 UTC by gothicx

Leapp packages that were installed with the Leapp utility are automatically added to the exclude list to prevent critical files from being removed 

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/upgrading_from_rhel_7_to_rhel_8/performing-post-upgrade-tasks-rhel-7-to-rhel-8_upgrading-from-rhel-7-to-rhel-8#doc-wrapper

2024-01-29 17:08 UTC, djdanielsson reviewed
I think changing from package to yum and then using excludes option if passing blank excludes then allows it to be removed is a lot better then using a command to do this. if that doesn't work (someone would need to test to verify) then there are some other changes that would be required for lint... speaking of which.... just realized that isn't working....

2024-01-29 17:08 UTC, djdanielsson requested changes
see comment

2024-03-27 13:40 UTC, djdanielsson commented
yum module actually has disable_excludes option which I think is better, if you update to use that then I will approve

2024-04-16 04:53 UTC, jeffmcutter commented
This is already present.  https://github.com/redhat-cop/infra.leapp/blob/main/roles/upgrade/tasks/leapp-post-upgrade.yml#L3

2024-04-30 13:53 UTC, swapdisk commented
As Jeffery noted, the `Clean dnf exclude list` task earlier in this task file is already doing this.

2024-04-30 13:53 UTC, closed without merging