Adding cacheable variable to parse_leapp_report
redhat-cop/infra.leapp pull request #223
Opened 2024-09-22 15:24 UTC by kalsto

Adding a variablized argument to allow this to be run from AAP and capture the reporting when an aggregator isn't available.

2024-09-30 17:46 UTC, swapdisk requested changes
The CI workflow caught some issues. Fix your yaml indenting and add a changelog fragment file.

2024-10-08 07:55 UTC, jeffmcutter commented
The newly introduced var also should be added to the role README.md.

2024-10-23 13:31 UTC, djdanielsson commented
it looks like your rebase went bad and you pulled in a lot of the other recent PRs changes as well. at this point I am not sure if it would be easier to start fresh and then add your changes back in from there.

2024-10-23 13:51 UTC, kalsto commented
Fixed the lint issue, updated the readme, and thank you @swapdisk for helping me fix my rebase issue!

2024-10-23 14:33 UTC, djdanielsson requested changes

2024-10-23 14:33 UTC, djdanielsson commented on roles/parse_leapp_report/README.md
> -| result_filename_json    | "{{ result_filename_prefix }}.json | JSON filename using the selected "result_filename_prefix" |
Looks like you deleted this line, can you put it back because it doesn't look like it should be deleted then it looks good

2024-10-23 14:34 UTC, djdanielsson commented on roles/parse_leapp_report/tasks/main.yml
> +  cacheable: "{{ result_fact_cacheable }}"
you need to fix the spacing here as well

2024-11-07 05:40 UTC, closed without merging