Ensure leapp_upgrade_repositories.repo uses local_repos_leapp
redhat-cop/infra.leapp pull request #226
Opened 2024-10-02 14:50 UTC by rjo-uk

A possible fix for https://github.com/redhat-cop/infra.leapp/issues/225 

This change ensures that before modifying `/etc/leapp/files/leapp_upgrade_repositories.repo` the file is removed.  This is to ensure that no old repositories are configured in this file, and it's contents are fully managed by the role.

2024-10-02 19:04 UTC, swapdisk requested changes

2024-10-02 19:04 UTC, swapdisk commented on changelogs/fragments/leapp_upgrade_repositories_content_from_var
Filename needs `.yml` suffix.

2024-10-08 07:49 UTC, jeffmcutter commented
@rjo-uk I added a reply to the issue.  If you would like to make those changes in this PR that would be great.  If not, I can clean up after myself once this is merged in.

2024-10-10 05:38 UTC, jeffmcutter commented
https://github.com/redhat-cop/infra.leapp/pull/228 addresses this and simplifies/consolidates the yum_repository tasks.

2024-10-10 05:38 UTC, closed without merging